import { Item } from "./item";

export const ITEMS: Item[] = [
	{ id: 0, name: `Karil's coif` },
	{ id: 1, name: `Ahrim's hood` },
	{ id: 2, name: `Dharok's helm` },
	{ id: 3, name: `Guthan's helm` },
	{ id: 4, name: `Torag's helm` },
	{ id: 5, name: `Verac's helm` },
	{ id: 6, name: `Karil's leathertop` },
	{ id: 7, name: `Ahrim's robetop` },
	{ id: 8, name: `Dharok's platebody` },
	{ id: 9, name: `Guthan's platebody` },
	{ id: 10, name: `Torag's platebody` },
	{ id: 11, name: `Verac's brassard` },
	{ id: 12, name: `Karil's leatherskirt` },
	{ id: 13, name: `Ahrim's robeskirt` },
	{ id: 14, name: `Dharok's platelegs` },
	{ id: 15, name: `Guthan's chainskirt` },
	{ id: 16, name: `Torag's platelegs` },
	{ id: 17, name: `Verac's plateskirt` },
	{ id: 18, name: `Karil's crossbow` },
	{ id: 19, name: `Ahrim's staff` },
	{ id: 20, name: `Dharok's greataxe` },
	{ id: 21, name: `Guthan's warspear` },
	{ id: 22, name: `Torag's hammers` },
	{ id: 23, name: `Verac's flail` },
	{ id: 24, name: `Pharaoh's sceptre` },
	{ id: 25, name: `Black mask` },
	{ id: 26, name: `Xeric's talisman` },
	{ id: 27, name: `Dragon warhammer` },
	{ id: 28, name: `Rune pouch` },
	{ id: 29, name: `Blood shard` },
	{ id: 30, name: `Bow of faerdhinen` },
	{ id: 31, name: `` },
	{ id: 32, name: `` },
	{ id: 33, name: `` },
	{ id: 34, name: `` },
	{ id: 35, name: `` },
	{ id: 36, name: `` },
	{ id: 37, name: `` },
	{ id: 38, name: `` },
	{ id: 39, name: `` },
	{ id: 40, name: `` },
	{ id: 41, name: `` },
	{ id: 42, name: `` },
	{ id: 43, name: `` },
	{ id: 44, name: `` },
	{ id: 45, name: `` },
	{ id: 46, name: `` },
	{ id: 47, name: `` },
	{ id: 48, name: `` },
	{ id: 49, name: `` },
];